[workspace]
members = [
    "adapter_pattern",
    "factory_pattern",
    "iterator_pattern",
    "singleton_pattern",
    "template_pattern"
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
